#!/usr/bin/env python
"""
Chunk preparation for large-scale Rubin feature generation.

Scans a local Rubin parquet export (DP1 directory or DP2 pre-joined file),
filters to objects with enough valid detections, and splits the eligible
object IDs into fixed-size chunk CSVs. These chunks feed the per-chunk
``generate-features-rubin`` calls generated by
``generate-features-rubin-slurm``.

Usage:
    prepare-rubin-chunks --data-path /path/to/dp1_data/ \
        --chunk-size 5000 --min-n-lc-points 50 --output-dir rubin_chunks

    prepare-rubin-chunks --release dp2 --data-path /path/to/edp2_data/VarCands_DP2.parquet \
        --chunk-size 5000 --min-n-lc-points 50 --output-dir rubin_chunks
"""

import argparse
import os
import pathlib
import pandas as pd

from scope.utils import parse_load_config
from scope.surveys.rubin import make_rubin_client

BASE_DIR = pathlib.Path.cwd()


def prepare_chunks(
    data_path=None,
    release=None,
    use_dia=False,
    flux_column=None,
    bands=None,
    chunk_size=5000,
    min_n_lc_points=50,
    output_dir="rubin_chunks",
):
    """
    Scan a local Rubin export and split eligible objects into chunk CSVs.

    Parameters
    ----------
    data_path : str, optional
        Path to the local export. DP1: directory containing
        Object/ForcedSource/Visit parquet files. DP2: the pre-joined
        parquet file (or its directory). Overrides config/env if given.
    release : str, optional
        'dp1' (default) or 'dp2'. Falls back to config/RUBIN_RELEASE.
    use_dia : bool, optional
        DP1 only: scan DiaObject + ForcedSourceOnDiaObject instead of
        Object + ForcedSource.
    flux_column : str, optional
        DP2 only: 'psfFlux' (default) or 'psfDiffFlux'.
    bands : list of str, optional
        Restrict the detection count to these bands. If None, all bands.
    chunk_size : int, optional
        Number of objects per chunk CSV (default 5000).
    min_n_lc_points : int, optional
        Minimum number of valid detections required to keep an object
        (default 50).
    output_dir : str, optional
        Directory to write chunk_*.csv and all_eligible_objectids.csv
        (default 'rubin_chunks').

    Returns
    -------
    pandas.DataFrame
        The eligible objects (objectId, coord_ra, coord_dec).
    """
    config = parse_load_config()
    rubin_config = dict(config.get("rubin", {}))
    if data_path is not None:
        if (release or rubin_config.get("release", "dp1")).lower() == "dp2":
            rubin_config["dp2_data_path"] = data_path
        else:
            rubin_config["data_path"] = data_path
    if flux_column is not None:
        rubin_config["flux_column"] = flux_column

    client = make_rubin_client(config=rubin_config, use_dia=use_dia, release=release)
    if not hasattr(client, "get_eligible_objects"):
        raise ValueError(
            "prepare-rubin-chunks requires a local parquet backend "
            "(RubinLocalClient, RubinLocalDiaClient, or RubinLocalDP2Client); "
            "set rubin.data_path (or rubin.dp2_data_path for --release dp2)."
        )

    print(f"Scanning local export for objects with >= {min_n_lc_points} detections...")
    objects = client.get_eligible_objects(min_n_lc_points=min_n_lc_points, bands=bands)
    print(f"Found {len(objects)} eligible objects.")

    rows = [
        {
            "objectId": oid,
            "coord_ra": info.get("coord_ra"),
            "coord_dec": info.get("coord_dec"),
        }
        for oid, info in objects.items()
    ]
    all_df = pd.DataFrame(rows).sort_values("objectId").reset_index(drop=True)

    output_path = pathlib.Path(output_dir)
    os.makedirs(output_path, exist_ok=True)

    master_path = output_path / "all_eligible_objectids.csv"
    all_df.to_csv(master_path, index=False)
    print(f"Saved master list of {len(all_df)} objects to {master_path}")

    n_total = len(all_df)
    n_chunks = (n_total + chunk_size - 1) // chunk_size if n_total > 0 else 0
    for chunk_idx in range(n_chunks):
        start = chunk_idx * chunk_size
        end = min(start + chunk_size, n_total)
        chunk_path = output_path / f"chunk_{chunk_idx:03d}.csv"
        all_df.iloc[start:end].to_csv(chunk_path, index=False)

    print(f"Wrote {n_chunks} chunk file(s) to {output_path} (chunk size {chunk_size}).")

    return all_df


def get_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Scan a local Rubin parquet export, filter to objects with "
            "enough detections, and split into chunk CSVs for SLURM."
        )
    )
    parser.add_argument(
        "--data-path",
        type=str,
        default=None,
        help=(
            "Path to the local export. DP1: directory with "
            "Object/ForcedSource/Visit parquet files. DP2: the pre-joined "
            "parquet file (or its directory). Overrides config/env."
        ),
    )
    parser.add_argument(
        "--release",
        type=str,
        default=None,
        choices=["dp1", "dp2"],
        help="Rubin data release to read (default: dp1, or config/RUBIN_RELEASE)",
    )
    parser.add_argument(
        "--use-dia",
        action="store_true",
        default=False,
        help="DP1 only: scan DiaObject + ForcedSourceOnDiaObject tables",
    )
    parser.add_argument(
        "--flux-column",
        type=str,
        default=None,
        choices=["psfFlux", "psfDiffFlux"],
        help="DP2 only: flux column to use for the detection count",
    )
    parser.add_argument(
        "--bands",
        type=str,
        nargs="+",
        default=None,
        help="Restrict the detection count to these bands (default: all)",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=5000,
        help="Number of objects per chunk CSV (default 5000)",
    )
    parser.add_argument(
        "--min-n-lc-points",
        type=int,
        default=50,
        help="Minimum valid detections required to keep an object (default 50)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="rubin_chunks",
        help="Directory to write chunk CSVs (default 'rubin_chunks')",
    )
    return parser


def main():
    parser = get_parser()
    args, _ = parser.parse_known_args()

    prepare_chunks(
        data_path=args.data_path,
        release=args.release,
        use_dia=args.use_dia,
        flux_column=args.flux_column,
        bands=args.bands,
        chunk_size=args.chunk_size,
        min_n_lc_points=args.min_n_lc_points,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    main()
